apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupo2diplomado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grupo2diplomado
  template:
    metadata:
      labels:
        app: grupo2diplomado
    spec:
      containers:
        - name: grupo2diplomado
          image: juanmarulanda/grupo2diplomado:1.0
          ports:
            - containerPort: 3000

