# Default values for grupo2diplomado-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  #repository: nginx
  #pullPolicy: IfNotPresent
  repository: juanmarulanda/grupo2diplomado
  name: grupo2diplomado
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.10

service:
    type: ClusterIP
    port: 80
