apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grupo2diplomado-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grupo2diplomado
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60